### ISSUE TITLE
[ANCHORE] Unsolicited random wisdom of the moment

### ISSUE THREAD

**Issue by popey** [popey/anchorectl-test#1]
```
details:
  msg: The true sign of intelligence is not knowledge but imagination - Albert Einstein
id: c2c5fc8ca51646269cf0904ebfce58d5
level: info
message: Unsolicited random wisdom of the moment
resource:
  account_name: admin
  id: null
  type: wisdom
source:
  base_url: http://api:8228
  host_id: anchore-quickstart
  request_id: null
  service_name: apiext
timestamp: '2024-07-10T13:11:19.982863'
type: system.test.random_wisdom
```
